# Backup directory where database dumps will be stored
backup_dir: "./backups"

# List of databases to backup
databases:
  - type: postgres
    host: localhost
    port: 5432
    username: postgres
    password: your_password
    database: mydb
    alias: "production-db"  # Optional: custom name for backup files

  - type: mysql
    host: localhost
    port: 3306
    username: root
    password: your_password
    database: mydb
    # No alias specified - will use database name "mydb" in filename

  - type: mariadb
    host: localhost
    port: 3306
    username: root
    password: your_password
    database: mydb
    alias: "customer-data"  # Optional: custom name for backup files

  - type: redis
    host: localhost
    port: 6379
    password: your_password  # Optional, leave empty if no auth
    database: "0"  # Redis database number (0-15)
    alias: "cache-db"  # Optional: custom name for backup files
